import { University } from "@/utils/commonTypes"
import { NextResponse } from "next/server"

const schools: University[] = [
  {
    "id": "1",
    "name": "Bogazici University",
    "type": "state",
    "gradeType": "bachelor",
    "educationType": "full time",
    "campusType": "on",
    "primaryLanguage": "Turkish",
    "country": "Turkey",
    "yearsOfStudy": 4,
    "deadlineForApplication": "2023-05-01",
    "season": "2023 Fall",
    "amount": 15000,
    "course": "Computer Science"
  },
  {
    "id": "2",
    "name": "Istanbul Technical University",
    "type": "state",
    "gradeType": "master",
    "educationType": "evening",
    "campusType": "on",
    "primaryLanguage": "Turkish",
    "country": "Turkey",
    "yearsOfStudy": 2,
    "deadlineForApplication": "2023-06-15",
    "season": "2023 Fall",
    "amount": 12000,
    "course": "Information Science"
  },
  {
    "id": "3",
    "name": "Sabanci University",
    "type": "private",
    "gradeType": "PhD",
    "educationType": "online",
    "campusType": "off",
    "primaryLanguage": "English",
    "country": "Turkey",
    "yearsOfStudy": 5,
    "deadlineForApplication": "2023-04-30",
    "season": "2023 Fall",
    "amount": 18000,
    "course": "Software Engineering"
  },
  {
    "id": "4",
    "name": "Manipal Academy of Higher Education",
    "type": "private",
    "gradeType": "associate",
    "educationType": "evening",
    "campusType": "off",
    "primaryLanguage": "English",
    "country": "India",
    "yearsOfStudy": 2,
    "deadlineForApplication": "2023-07-01",
    "season": "2023 Fall",
    "amount": 10000,
    "course": "English",
  },
  {
    "id": "5",
    "name": "Indian Institute of Technology Delhi",
    "type": "state",
    "gradeType": "bachelor",
    "educationType": "full time",
    "campusType": "on",
    "primaryLanguage": "English",
    "country": "India",
    "yearsOfStudy": 4,
    "deadlineForApplication": "2023-05-20",
    "season": "2023 Fall",
    "amount": 16000,
    "course": "Mathematics"
  },
  {
    "id": "6",
    "name": "University of Malaya",
    "type": "state",
    "gradeType": "master",
    "educationType": "full time",
    "campusType": "on",
    "primaryLanguage": "Malay",
    "country": "Malaysia",
    "yearsOfStudy": 2,
    "deadlineForApplication": "2023-06-30",
    "season": "2023 Fall",
    "amount": 13000,
    "course": "Physics"
  },
  {
    "id": "7",
    "name": "Universiti Teknologi Malaysia",
    "type": "state",
    "gradeType": "PhD",
    "educationType": "online",
    "campusType": "off",
    "primaryLanguage": "English",
    "country": "Malaysia",
    "yearsOfStudy": 5,
    "deadlineForApplication": "2023-07-15",
    "season": "2023 Fall",
    "amount": 20000,
    "course": "Chemistry"
  },
  {
    "id": "8",
    "name": "Near East University",
    "type": "private",
    "gradeType": "associate",
    "educationType": "full time",
    "campusType": "on",
    "primaryLanguage": "English",
    "country": "Northern Cyprus",
    "yearsOfStudy": 2,
    "deadlineForApplication": "2023-08-01",
    "season": "2023 Fall",
    "amount": 11000,
    "course": "Biology"
  },
  {
    "id": "9",
    "name": "Eastern Mediterranean University",
    "type": "state",
    "gradeType": "bachelor",
    "educationType": "evening",
    "campusType": "on",
    "primaryLanguage": "English",
    "country": "Northern Cyprus",
    "yearsOfStudy": 4,
    "deadlineForApplication": "2023-05-15",
    "season": "2023 Fall",
    "amount": 17000,
    "course": "Health Management"
  },
  {
    "id": "10",
    "name": "Taras Shevchenko National University of Kyiv",
    "type": "state",
    "gradeType": "master",
    "educationType": "full time",
    "campusType": "on",
    "primaryLanguage": "Ukrainian",
    "country": "Ukraine",
    "yearsOfStudy": 2,
    "deadlineForApplication": "2023-06-20",
    "season": "2023 Fall",
    "amount": 14000,
    "course": "Nursing"
  },
  {
    "id": "11",
    "name": "Lviv Polytechnic National University",
    "type": "state",
    "gradeType": "PhD",
    "educationType": "online",
    "campusType": "off",
    "primaryLanguage": "Ukrainian",
    "country": "Ukraine",
    "yearsOfStudy": 5,
    "deadlineForApplication": "2023-07-30",
    "season": "2023 Fall",
    "amount": 22000,
    "course": "Medicine"
  },
  {
    "id": "12",
    "name": "University of Sarajevo",
    "type": "state",
    "gradeType": "associate",
    "educationType": "full time",
    "campusType": "on",
    "primaryLanguage": "Bosnian",
    "country": "Bosnia",
    "yearsOfStudy": 2,
    "deadlineForApplication": "2023-08-15",
    "season": "2023 Fall",
    "amount": 12000,
    "course": "Dentistry"
  },
  {
    "id": "13",
    "name": "University of Mostar",
    "type": "state",
    "gradeType": "bachelor",
    "educationType": "evening",
    "campusType": "on",
    "primaryLanguage": "Bosnian",
    "country": "Bosnia",
    "yearsOfStudy": 4,
    "deadlineForApplication": "2023-05-10",
    "season": "2023 Fall",
    "amount": 18000,
    "course": "Pharmacy"
  },
  {
    "id": "14",
    "name": "Cyprus International University",
    "type": "private",
    "gradeType": "associate",
    "educationType": "evening",
    "campusType": "on",
    "primaryLanguage": "English",
    "country": "Northern Cyprus",
    "yearsOfStudy": 2,
    "deadlineForApplication": "2023-08-10",
    "season": "2023 Fall",
    "amount": 11000,
    "course": "Business Administration"
  },
  {
    "id": "15",
    "name": "Kharkiv National University of Radio Electronics",
    "type": "state",
    "gradeType": "bachelor",
    "educationType": "full time",
    "campusType": "on",
    "primaryLanguage": "Ukrainian",
    "country": "Ukraine",
    "yearsOfStudy": 4,
    "deadlineForApplication": "2023-06-25",
    "season": "2023 Fall",
    "amount": 17000,
    "course": "Information Technology"
  },
  {
    "id": "16",
    "name": "University of Zenica",
    "type": "state",
    "gradeType": "master",
    "educationType": "online",
    "campusType": "off",
    "primaryLanguage": "Bosnian",
    "country": "Bosnia",
    "yearsOfStudy": 2,
    "deadlineForApplication": "2023-07-01",
    "season": "2023 Fall",
    "amount": 13000,
    "course": "Environmental Science"
  },
]



export async function GET(request: Request) {
  return NextResponse.json({ schools })
}